[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"
authors = ["Aaron Gobeyn"]
license = "GNU GENERAL PUBLIC LICENSE"

[dependencies]
log = "0.4.22"
env_logger = "0.11.5"
chrono = "0.4.38"
indicatif = "0.17.8"
rand = "0.8.5"
